substitutions:
  _ARTIFACT_REGISTRY: qualitytime
  _REGION: us-west1
  _SERVICE_ACCOUNT: qualitytime-sa
  _SERVICE_NAME: quality-time-staging
  _IMAGE_NAME: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}

options:
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --cache-from
      - ${_IMAGE_NAME}:latest
      - -t
      - ${_IMAGE_NAME}:$COMMIT_SHA
      - -t
      - ${_IMAGE_NAME}:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - --all-tags
      - ${_IMAGE_NAME}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - ${_IMAGE_NAME}:$COMMIT_SHA
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --service-account
      - ${_SERVICE_ACCOUNT}@$PROJECT_ID.iam.gserviceaccount.com
      - --port
      - "8080"

images:
  - ${_IMAGE_NAME}:$COMMIT_SHA
  - ${_IMAGE_NAME}:latest
